### ISSUE TITLE
Progress animation repeats multiple times

### ISSUE THREAD

**Issue by LuisOlazo** [vanskarner/SingleAdapter#2]
Tried with 150 milliseconds asynchronous data request, but progress animation repeats when requesting consecutively

https://user-images.githubusercontent.com/99571364/153737873-d436cc37-1298-40a5-9e6e-93bf4a2a9ddd.mp4

.

**Comment by vanskarner** [comment]
The problem has been corrected :grin: , the changes can be found in:  015f5d1bc77b09b5f34ee10e915685c6f5abdd21
Mainly the method `showProgress()` was modified in this way:
```java
    public void showProgress() {
        if (isEnableLoad()) {
            List<BindItem> updateList = createItems();
            updateList.remove(loadItem);
            updateList.add(loadItem);
            listDiffer.submitList(updateList);
        }
    }
```
